#!/usr/bin/env bash
#
# Rebuild a bootable qcow2 image from a sanitized capture.
# Runs on the maintainer's machine, NOT on the volunteer's NAS.
#
# Strategy:
#   1. Verify manifest, reassemble sanitized tarball.
#   2. Read inventory.json to learn partition layout, kernel name, cmdline.
#   3. Create a qcow2, partition it (single ext4 root + optional EFI).
#   4. Extract the sanitized rootfs into the root partition.
#   5. Install GRUB (or systemd-boot) so the image boots in qemu/kvm.
#   6. Print a ready-to-run qemu command.

set -Eeuo pipefail

IN=""
OUT=""
SIZE="40G"
ARCH=""

usage() {
    cat <<'USAGE'
Usage: rebuild_qcow2.sh --in <sanitized-dir> --out <image.qcow2> [options]

  --in <dir>      Directory produced by sanitize.sh.
  --out <file>    Output qcow2 path.
  --size <size>   Virtual disk size (default: 40G).
  --arch <arch>   Target arch (default: derived from inventory.json).
  -h, --help      Show this help.

Requirements on the host:
  qemu-img, qemu-system-x86_64 (or aarch64), parted, e2fsprogs, grub2,
  zstd, jq, sudo, util-linux losetup, rsync.

This script uses loop devices and needs sudo.
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --in)    IN="$2"; shift 2 ;;
        --out)   OUT="$2"; shift 2 ;;
        --size)  SIZE="$2"; shift 2 ;;
        --arch)  ARCH="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown arg: $1" >&2; usage; exit 2 ;;
    esac
done

[[ -z "$IN" || -z "$OUT" ]] && { usage; exit 2; }
[[ ! -d "$IN" ]] && { echo "ERROR: --in not found: $IN" >&2; exit 3; }

for tool in qemu-img parted mkfs.ext4 zstd jq rsync losetup; do
    command -v "$tool" >/dev/null 2>&1 || { echo "missing tool: $tool" >&2; exit 4; }
done

INV="$IN/inventory.json"
[[ -f "$INV" ]] || { echo "ERROR: inventory.json missing in --in" >&2; exit 3; }

KERNEL_REL="$(jq -r '.kernel' "$INV")"
CMDLINE="$(jq -r '.cmdline' "$INV")"
[[ -z "$ARCH" ]] && ARCH="$(jq -r '.arch' "$INV")"

echo "[*] target arch: $ARCH"
echo "[*] kernel release in capture: $KERNEL_REL"
echo "[*] original cmdline: $CMDLINE"

WORK="$(mktemp -d -t ugos-rebuild.XXXXXX)"
# Track the SPECIFIC nbd device this script uses so cleanup never touches
# unrelated loop/nbd devices the maintainer might have in use.
NBD=""
cleanup() {
    local rc=$?
    set +e
    if [[ -n "$WORK" && -d "$WORK/mnt" ]]; then
        sudo umount -R "$WORK/mnt" 2>/dev/null
    fi
    if [[ -n "$NBD" ]]; then
        sudo qemu-nbd --disconnect "$NBD" 2>/dev/null
    fi
    rm -rf "$WORK"
    return $rc
}
trap cleanup EXIT

echo "[*] reassembling sanitized tarball"
CHUNKS=( "$IN"/sanitized.tar.zst.* )
[[ -e "${CHUNKS[0]}" ]] || { echo "ERROR: no sanitized.tar.zst.* chunks" >&2; exit 5; }

# --- Create qcow2 + partition ---
echo "[*] creating qcow2 ($SIZE) -> $OUT"
qemu-img create -f qcow2 "$OUT" "$SIZE" >/dev/null

if ! lsmod | grep -q '^nbd'; then sudo modprobe nbd max_part=8; fi
# Find the first nbd device that is NOT already in use. We never touch
# nbd devices we didn't pick ourselves.
NBD=""
for i in /sys/class/block/nbd*; do
    nbd_name="$(basename "$i")"
    if [[ "$(cat "$i/size" 2>/dev/null)" == "0" ]]; then
        NBD="/dev/$nbd_name"
        break
    fi
done
if [[ -z "$NBD" ]]; then
    echo "ERROR: no free /dev/nbd* device available" >&2
    exit 6
fi
echo "[*] using $NBD"
sudo qemu-nbd --connect="$NBD" "$OUT"

echo "[*] partitioning (GPT, EFI 512M + root rest)"
sudo parted -s "$NBD" mklabel gpt
sudo parted -s "$NBD" mkpart EFI fat32 1MiB 513MiB
sudo parted -s "$NBD" set 1 esp on
sudo parted -s "$NBD" mkpart root ext4 513MiB 100%
sudo partprobe "$NBD"
sleep 1

sudo mkfs.vfat -F32 "${NBD}p1" >/dev/null
sudo mkfs.ext4 -F -L UGOS_VM "${NBD}p2" >/dev/null

mkdir -p "$WORK/mnt"
sudo mount "${NBD}p2" "$WORK/mnt"
sudo mkdir -p "$WORK/mnt/boot/efi"
sudo mount "${NBD}p1" "$WORK/mnt/boot/efi"

# --- Extract sanitized rootfs ---
echo "[*] extracting sanitized rootfs into image (this takes a while)"
cat -- "${CHUNKS[@]}" | zstd -d -T0 \
  | sudo tar -x --acls --xattrs --numeric-owner -C "$WORK/mnt"

# --- Generate a fresh fstab targeting the new partitions ---
EFI_UUID="$(sudo blkid -s UUID -o value "${NBD}p1")"
ROOT_UUID="$(sudo blkid -s UUID -o value "${NBD}p2")"

sudo tee "$WORK/mnt/etc/fstab.vm" >/dev/null <<EOF
# VM-specific fstab generated by rebuild_qcow2.sh
UUID=${ROOT_UUID}  /          ext4  defaults,errors=remount-ro  0 1
UUID=${EFI_UUID}   /boot/efi  vfat  defaults                    0 2
EOF
sudo mv -- "$WORK/mnt/etc/fstab.vm" "$WORK/mnt/etc/fstab"

# --- Install GRUB inside a chroot ---
echo "[*] installing GRUB inside the image"
for d in dev dev/pts proc sys run; do
    sudo mkdir -p "$WORK/mnt/$d"
    sudo mount --bind "/$d" "$WORK/mnt/$d"
done

# Best-effort grub install. If the captured rootfs has grub binaries, use them.
if sudo chroot "$WORK/mnt" /bin/sh -c 'command -v grub-install' >/dev/null 2>&1; then
    sudo chroot "$WORK/mnt" /bin/sh -c \
        "grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=UGOSVM --recheck \
         && update-grub"
else
    echo "WARNING: grub not available in captured rootfs; you'll need to boot via -kernel/-initrd directly."
fi

sudo umount -R "$WORK/mnt"
sudo qemu-nbd --disconnect "$NBD"
NBD=""  # so the EXIT trap doesn't re-disconnect

KERNEL_PATH=""
INITRD_PATH=""
# Pull kernel+initrd out separately so the user has a fallback boot path.
mkdir -p "$WORK/extracted-boot"
cat -- "${CHUNKS[@]}" | zstd -d -T0 \
  | tar -x -C "$WORK/extracted-boot" --wildcards \
        "./boot/vmlinuz-*" "./boot/initrd*" 2>/dev/null || true

KERNEL_PATH="$(ls "$WORK/extracted-boot/boot/"vmlinuz-* 2>/dev/null | head -1 || true)"
INITRD_PATH="$(ls "$WORK/extracted-boot/boot/"initrd* 2>/dev/null | head -1 || true)"

echo
echo "[+] rebuild complete: $OUT"
echo
echo "Boot the image with one of:"
echo
echo "  # native UEFI boot (works if GRUB installed cleanly)"
echo "  qemu-system-x86_64 -enable-kvm -m 4G -smp 4 \\"
echo "    -bios /usr/share/OVMF/OVMF_CODE.fd \\"
echo "    -drive file='$OUT',if=virtio \\"
echo "    -net nic,model=virtio -net user,hostfwd=tcp::2222-:22 \\"
echo "    -nographic"
echo
if [[ -n "$KERNEL_PATH" && -n "$INITRD_PATH" ]]; then
echo "  # direct kernel boot fallback"
echo "  qemu-system-x86_64 -enable-kvm -m 4G -smp 4 \\"
echo "    -kernel '$KERNEL_PATH' -initrd '$INITRD_PATH' \\"
echo "    -append 'root=UUID=${ROOT_UUID} rw console=ttyS0' \\"
echo "    -drive file='$OUT',if=virtio \\"
echo "    -nographic"
fi
echo
echo "Root password inside the VM is whatever was passed to sanitize.sh --root-pw."
