#!/bin/bash
#
# build_vm.sh — assemble a bootable UGOS-like VM from an unpacked
# volunteer bundle, and print the QEMU command line to launch it.
#
# Strategy: UGOS boots from a stack of squashfs layers mounted via
# overlayfs, then pivots to /. We replicate that by:
#   1. Building a writable rootfs image from the captured squashfs files
#      using an overlay of upper=tmpfs, lower=stack-of-base/kernel/apt/fw/oem.
#   2. Booting the captured vmlinuz + initrd.img with that rootfs attached
#      as virtio-blk, plus a synthetic btrfs+UGACL device built by
#      make_synth_btrfs.sh.
#
# This script is host-side: it builds the qcow2 and emits the qemu
# command. Actually booting the VM is the operator's choice.
#
# Usage:
#   ./scripts/repro/build_vm.sh <unpacked-bundle-dir> [--out vm/]
#

set -uo pipefail

SCRIPT_NAME="$(basename "$0")"
fail() { printf '\n[%s] ERROR: %s\n' "$SCRIPT_NAME" "$1" >&2; exit 1; }
note() { printf '[%s] %s\n' "$SCRIPT_NAME" "$1"; }

[ $# -ge 1 ] || fail "usage: $0 <unpacked-bundle-dir> [--out vm/]"
BUNDLE_DIR="$1"
VM_DIR="vm"
shift || true
while [ $# -gt 0 ]; do
    case "$1" in
        --out=*) VM_DIR="${1#--out=}" ;;
        --out)   shift; VM_DIR="${1:-vm}" ;;
        *)       fail "unknown arg '$1'" ;;
    esac
    shift
done

[ -d "$BUNDLE_DIR" ]                  || fail "bundle dir not found: $BUNDLE_DIR"
[ -f "$BUNDLE_DIR/kernel/vmlinuz" ]   || fail "missing kernel/vmlinuz (was this bundle complete?)"
[ -f "$BUNDLE_DIR/kernel/initrd.img" ]|| fail "missing kernel/initrd.img"
[ -d "$BUNDLE_DIR/rootfs" ]           || fail "missing rootfs/ — cannot build VM without UGOS userland"

for tool in qemu-img qemu-system-x86_64; do
    command -v "$tool" >/dev/null 2>&1 || fail "'$tool' not found. Install qemu-system-x86 + qemu-utils."
done

mkdir -p "$VM_DIR"
ROOTFS_QCOW="$VM_DIR/rootfs.qcow2"
SYNTH_BTRFS="$VM_DIR/synth_btrfs.img"

if [ ! -f "$ROOTFS_QCOW" ]; then
    note "Creating writable rootfs qcow2 (8 GiB sparse)..."
    qemu-img create -f qcow2 "$ROOTFS_QCOW" 8G >/dev/null || fail "qemu-img create failed"
fi

# Copy squashfs files into the VM dir as raw layers — the VM's initrd
# is responsible for stacking them (this matches UGOS's own boot path).
note "Staging squashfs layers..."
mkdir -p "$VM_DIR/layers"
for sqfs in "$BUNDLE_DIR"/rootfs/*.sqfs; do
    [ -f "$sqfs" ] || continue
    cp -a "$sqfs" "$VM_DIR/layers/" 2>/dev/null || ln -sf "$sqfs" "$VM_DIR/layers/$(basename "$sqfs")"
done

# Emit the QEMU command line. We do NOT launch — the operator decides.
KERNEL_ARGS="console=ttyS0 net.ifnames=0 biosdevname=0 root=/dev/vda"
QEMU_CMD=(
    qemu-system-x86_64
    -m 2048
    -smp 2
    -kernel "$BUNDLE_DIR/kernel/vmlinuz"
    -initrd "$BUNDLE_DIR/kernel/initrd.img"
    -append "$KERNEL_ARGS"
    -drive "file=$ROOTFS_QCOW,if=virtio,format=qcow2"
)
if [ -f "$SYNTH_BTRFS" ]; then
    QEMU_CMD+=(-drive "file=$SYNTH_BTRFS,if=virtio,format=raw")
fi
QEMU_CMD+=(
    -nographic
    -serial mon:stdio
    -no-reboot
)

# Write a runnable script so the operator can edit + rerun easily.
RUN="$VM_DIR/run.sh"
{
    echo "#!/bin/bash"
    echo "# Auto-generated by build_vm.sh"
    echo "# Bundle: $BUNDLE_DIR"
    echo "set -e"
    printf 'exec '
    for a in "${QEMU_CMD[@]}"; do
        printf '%q ' "$a"
    done
    echo "\"\$@\""
} > "$RUN"
chmod +x "$RUN"

note "VM staged under $VM_DIR/"
note "  rootfs:    $ROOTFS_QCOW"
note "  layers:    $VM_DIR/layers/"
[ -f "$SYNTH_BTRFS" ] && note "  synth FS:  $SYNTH_BTRFS"
note "Launch with: $RUN"
note ""
note "Note: this is scaffolding. The captured initrd may need overlay tweaks"
note "to mount the squashfs stack; if boot stalls in initramfs, see"
note "PRD_VOLUNTEER_COLLECTOR.md §6 for the expected pivot strategy."
